### ISSUE TITLE
Spaltenbreite vergrössern, besonders bei Smartphone Ansicht

### ISSUE THREAD

**Issue by viviane-walker-uzh** [urban-sustainability-lab-zurich/sdgnets_homepage#8]
hello Myriam, 

Siehe unten das Bildschirmfoto. Die sehr schmale Spalte ist unangenehm/anstrengend zu lesen, da nur 1-3 Wörter pro Zeile stehen. Ich würde, wenn es geht die Spaltenbreite vergrössern, oder vielleicht allgemein die Leseansicht in Spalten auflösen und nur eine breite Spalte haben (wie gewöhnlich bei Webseiten). Was meinst du dazu:)?

<img width="447" alt="image" src="https://user-images.githubusercontent.com/108020771/201122976-7463ff57-3d29-4cd4-b40f-3c7beb2b313d.png">

**Comment by marioangst** [comment]
duplicate with #9
